Guide on fitlering on time
cultuurnet/apidocs pull request #407
Opened 2024-09-16 14:43 UTC by corneelwille

### Added
- Guide about filtering on time

---

Ticket: https://jira.uitdatabank.be/browse/PPF-551

2024-09-16 15:08 UTC, grubolsch requested changes

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +Since any overlap is a match with range queries, you can explicitely exclude anything that falls outside of your range using advanced queries. The query below will search for events happening in the
explicitely -> explicitly

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +Since any overlap is a match with range queries, you can explicitely exclude anything that falls outside of your range using advanced queries. The query below will look for events that take place in
explicitely -> explicitly

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +* `dateFrom`: returns only results that are happening / openafter the given date-time.
* `dateFrom`: returns only results that are happening / open after the given date-time.

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +## Filtering on availabilty date
## Filtering on availability date

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +* `created`: returns results that are created in a gived date range.
gived -> given

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +* `dateRange`: returns results that are happening / open in a gived date range.
gived -> given

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +* `localTimeRange`: returns results that are created in a gived date range.
gived -> given

2024-09-16 15:08 UTC, grubolsch commented on projects/uitdatabank/docs/search-api/filters/datetime.md
> +* `modified`: returns results that are created in a gived date range.
gived -> given

2024-09-16 16:09 UTC, corneelwille commented
@grubolsch all feedback processed with commit [08d6b3d](https://github.com/cultuurnet/apidocs/pull/407/commits/08d6b3dc8b205ae73e05315866aa3a219c049ffb)

2024-09-17 08:04 UTC, grubolsch approved these changes

2024-09-17 08:10 UTC, merged